import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Nav from "./nav";
import Footer from "./footer";
// import CursorFollower from "./cursorFollower"


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <body className={`${inter.className} font-suisse`}>
        <Nav />
        {/* <CursorFollower size={40} /> */}

        {children}
        <Footer />
      </body>
    </html>
  );
}
